server:
    port: 9088
spring:
    application:
        name: house
    cloud:
        nacos:
            discovery:
                server-addr: host.ownw.site:8848
management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        health:
            show-details: always